#ifndef CODE_TOKENTYPE_H
#define CODE_TOKENTYPE_H


enum class TokenType {
    END_OF_TEXT,
    MUT_KEYWORD,
    IF_KEYWORD,
    ELSE_KEYWORD,
    LOOP_KEYWORD,
    MATCH_KEYWORD,
    PATTERN_KEYWORD,
    IS_KEYWORD,
    FUNC_KEYWORD,
    NONE_KEYWORD,
    REF_KEYWORD,
    INT_KEYWORD,
    FLOAT_KEYWORD,
    STRING_KEYWORD,
    RETURN_KEYWORD,
    COMMENT,
    LEFT_BRACKET,
    RIGHT_BRACKET,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    SEMICOLON,
    COMMA,
    ASSIGN,
    EQUAL,
    NOT_EQUAL,
    GREATER_THAN,
    LESS_THAN,
    GREATER_OR_EQUAL,
    LESS_OR_EQUAL,
    NEGATION,
    PLUS,
    MINUS,
    ASTERISK,
    DIVISION,
    INT_DIVISION,
    MODULO,
    INTEGER_VALUE,
    FLOAT_VALUE,
    STRING_LITERAL,
    DOT,
    IDENTIFIER
};


#endif //CODE_TOKENTYPE_H
